# Generated by Django 4.0.2 on 2022-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
    ]
