# Generated by Django 4.0.2 on 2022-03-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_activity_name_alter_activity_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('all_private_event', 'Add, del, edit private event'), ('all_event', 'Add, del, edit all event'), ('edit_team_event', 'Edit team event'))},
        ),
    ]
