# Generated by Django 4.0.2 on 2022-04-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
