# Generated by Django 4.0.2 on 2022-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
