# Generated by Django 4.0.2 on 2022-03-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='short_name',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
